version: '3'
services:
  cloudflaredns:
    container_name: cloudflaredns
    pull_policy: build
    build: .
    restart: unless-stopped
    environment:
      - ZONE=${ZONE}
      - RECORDS=${RECORD}
      - TOKEN=${TOKEN}