version: '3'
services:
  cloudflaredns:
    container_name: cloudflaredns
    pull_policy: build
    build: .
    restart: unless-stopped
    environment:
      - ZONE=${ZONE}
      - RECORD=${RECORD}
      - TOKEN=${TOKEN}
      - NODE_ENV=${NODE_ENV}